


map_name: "CornerHallE"
n_laps: 1
<<<<<<< HEAD
speed_limit: 8
# directory: "/home/jetson/f1tenth_ws/src/f1tenth_racing/"
directory: "/home/benjy/sim_ws/src/f1tenth_racing/"

agent_name: "AgentOff_SAC_endToEnd_mco_TAL_8_1_0"
=======
speed_limit: 1
directory: "/home/jetson/f1tenth_ws/src/f1tenth_racing/"
# directory: "/home/benjy/sim_ws/src/f1tenth_racing/"

agent_name: "AgentOff_SAC_endToEnd_mco_TAL_8_5_0"
architecture: "endToEnd"
>>>>>>> master

# agent_name: "AgentOff_SAC_TrajectoryFollower_mco_TAL_8_1_0"

# agent_name: "AgentOff_SAC_Game_mco_TAL_8_1_0"

<<<<<<< HEAD
=======
# agent_name: "AgentOff_SAC_Game_mco_TAL_8_5_0"
# architecture: "planning"

#architecture: "pure_pursuit"
#agent_name: "PurePursuit"
>>>>>>> master
lookahead: 1.4
