


map_name: "CornerHallE"
n_laps: 1
speed_limit: 3

directory: "/home/jetson/f1tenth_ws/src/f1tenth_racing/"
results_directory: "Data/ResultsJetson24_2/"
odom_topic: "pf/pose/odom"


directory: "/home/benjy/sim_ws/src/f1tenth_racing/"
results_directory: "Data/ResultsRos24/"
odom_topic: "ego_racecar/odom"


#agent_name: "AgentOff_SAC_endToEnd_mco_TAL_8_1_0"
#agent_name: "AgentOff_SAC_TrajectoryFollower_mco_TAL_8_1_0"
agent_name: "AgentOff_SAC_Game_mco_TAL_8_1_0"

lookahead: 2.2
