


# map_name: "CornerHallE"
map_name: "aut"
n_laps: 10
speed_limit: 5

# directory: "/home/jetson/f1tenth_ws/src/f1tenth_racing/"
# results_directory: "Data/ResultsJetson25/"
# odom_topic: "pf/pose/odom"


directory: "/home/benjy/sim_ws/src/f1tenth_racing/"
results_directory: "Data/ResultsRos25_2/"
odom_topic: "ego_racecar/odom"


# agent_name: "AgentOff_SAC_endToEnd_mco_TAL_8_1_0"
agent_name: "AgentOff_SAC_TrajectoryFollower_mco_TAL_8_1_0"
# agent_name: "AgentOff_SAC_Game_mco_TAL_8_1_0"

lookahead: 1.4
