# testing



pure_pursuit:
  ros__parameters: 
    # map_name: "levine_blocked"
    map_name: "aut"
    n_laps: 2
    
nn_agent:
  ros__parameters:
    map_name: "aut"
    agent_name: "AgentOff_SAC_TrajectoryFollower_gbr_train_8_8_0"
    architecture: "trajectory"
    # agent_name: "AgentOff_SAC_Game_gbr_train_8_8_0"
    # architecture: "planning"
